services:
  api:
    build: .
    environment:
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/gtfs
    ports:
      - "3000:3000"

  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gtfs
    volumes:
      - db:/var/lib/postgresql/data
  
  redis:
    image: redis:6
    ports:
      - "6379:6379"

volumes:
  db:
