services:
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./.dev/postgres-data-2:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - "6379:6379"