app = "transit-tracker-api"
primary_region = "sea"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    soft_limit = 50

[metrics]
  port = 9090
  path = "/metrics"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
