app = "transit-tracker-api"
primary_region = "sea"
swap_size_mb = 512

[build.args]
  BUILD_FOR_FLY = "true"

[deploy]
  strategy = "bluegreen"
  release_command = '"pnpm sentry:sourcemaps ; pnpm gtfs:db:migrate"'

[env]
  GTFS_RT_MIN_CACHE_AGE = "15s"
  NODE_OPTIONS = "--max-old-space-size=512"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    soft_limit = 35
  
  [[http_service.checks]]
    grace_period = "5s"
    interval = "1m"
    method = "GET"
    timeout = "10s"
    path = "/healthz"

[metrics]
  port = 9090
  path = "/metrics"

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
