app = "transit-tracker-api"
primary_region = "sea"

[build]

[deploy]
  strategy = "bluegreen"
  release_command = "./node_modules/.bin/dbmate up && node dist/cli sync"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    soft_limit = 50
  
  [[http_service.checks]]
    grace_period = "5s"
    interval = "1m"
    method = "GET"
    timeout = "10s"
    path = "/healthz"

[metrics]
  port = 9090
  path = "/metrics"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
